name: Test
on:
  push:
    branches-ignore:
      - main
permissions:
  actions: read
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run affacted test(s)
        run: pnpm run test